pipeline{
	agent any
	//tools{
	//	dotnet 'dotnet-sdk-9.0'
	//}
	stages{
		stage('Checkout'){
			steps{
				git 'https://github.com/mertdal/JenkinsDeneme'
			}
		}
		stage('Build'){
			steps{
				dir('JenkinsDeneme1'){
					sh 'dotnet restore'
					sh 'dotnet build --configuration Release'
				}
			}
		}
	}
	post{
		success{
		'Build başarıyla tamamlandı.'
		}
		failure{
		'Build tamamlanırken sorun oluştu.'
		}
	}
}